### ISSUE TITLE
Colab notebook doesn't work: Import error

### ISSUE THREAD

**Issue by vdyma** [Kinyugo/consistency_models#1]
Hi!
Thanks for your work, however the Colab notebook doesn't work. I ran all the cells in order, but got an error: `ModuleNotFoundError: No module named 'consistency_models'`

**Comment by Kinyugo** [comment]
Hello, 

Try restarting the notebook after installing consistency_models should fix the error.

**Comment by vdyma** [comment]
Thanks, it did work. I have some other ideas on improving the notebook. I will create a PR later.
