### ISSUE TITLE
Pseudo Huber Loss

### ISSUE THREAD

**Issue by hao-pt** [Kinyugo/consistency_models#10]
Could you share some insights into why you use a fixed coefficient c like this: c = 0.00054 * math.sqrt(math.prod(input.shape[1:])) rather than a specific user's defined value like 0.001 in the paper.

**Comment by Kinyugo** [comment]
I obtained that specific scaling from table 1.

**Comment by hao-pt** [comment]
Thank you, I just found that in the paper.
