### ISSUE TITLE
Question about sigma_data

### ISSUE THREAD

**Issue by javiersgjavi** [Kinyugo/consistency_models#16]
Greetings,

First of all, thank you for such an amazing repository. It has been very helpful for me to understand the implementation of the consistency models document. However, I have a doubt that I cannot solve on my own:

In the paper I understood that sigma_data represents the standard deviation of the original data, but in the manuscript it is always set to 0.5. Furthermore, I get the impression that in your code you do not calculate the standard deviation for each data set, but simply set sigma_data to 0.5. So is it really the std of the data, a hyperparameter or a value that somehow represents the expected standard normalisation in this data?

**Comment by Kinyugo** [comment]
Hello @javiersgjavi  0.5 is a hyperparameter that is meant to represent the expected std of the data and is not actually computed.

**Comment by javiersgjavi** [comment]
Perfect, thank you very much for your clear and fast answer!
